### ISSUE TITLE
I'm not happy with the new update :(

### ISSUE THREAD

**Issue by BlvDeLxRd** [Sonath21/spotify-controls#10]
**_I'm not happy with the new update_**. do not consider it rude, but in order to switch to Spotify with a double click, it is inconvenient to use it, please make the switch of this parameter in the settings. and yet, a feature that users (at least me) really need: when switching to Spotify, you can go back with another mouse click

**Comment by BlvDeLxRd** [comment]
> Double click? You mean when you open the extension, you double click it and it opens and then closes right? Why would you double click when one click just opens it :p ? Or you mean that you click on the extension again as a shortcut, to quickly bring spotify to the foreground I guess? No problem though, I will add it as an option for users to pick between the new and old option. Thanks for your feedback! Meanwhile, if it really bothers you, you can just download version 8 from the extensions webpage.

Yes, I mean option 2

**Comment by Sonath21** [comment]
Option added! (version 10)
