### ISSUE TITLE
[Feature Request] Add Pause/Play with Middle Mouse Button and Options for Icon Customization

### ISSUE THREAD

**Issue by SuiziM** [Sonath21/spotify-controls#11]
First of all, thank you for your work on this extension—it has been incredibly useful! I’d like to suggest a couple of features that would make it even better:

- **Middle Mouse Button Pause/Play**: Enable users to pause or play Spotify by clicking the middle mouse button on the extension icon, avoiding the need to open or switch to the Spotify window.

- **Icon Customization:** Provide options to either :
   - Provide an option to hide the Spotify icon for a cleaner top bar 
   or
   - Offer the ability to switch to a symbolic icon, as the default green Spotify icon tends to stand out from the rest of the GNOME Shell theme.
 
I’m missing these features since switching from the GNOME MPRIS Label extension. Adding them would greatly enhance usability and integration.

**Comment by Sonath21** [comment]
Good suggestions, will implement when I find the time to do so!
