### ISSUE TITLE
[Feature Request] Support for Tidal Hifi

### ISSUE THREAD

**Issue by espensa** [Sonath21/spotify-controls#12]
https://github.com/Mastermindzh/tidal-hifi is a modified version of the Tidal web player for tighter Linux integration, and it supports MPRIS and has an API, and I was wondering if you'd consider adding it as an alternative player. I enjoy having player controls and track info on the status bar like in your extension rather than having to look into the notification dropdown, and I'd imagine adding support would be mostly just changing the targets for MPRIS and what window to watch for?

I guess if someone has both open being able to click to switch between the two could be an idea.

**Comment by Sonath21** [comment]
Hey, while its a good idea, i intend to keep this extension spotify exclusive, for now at least ( i doubt the implementation would be hard for what youre asking, but there would be the edge cases where both apps are open, and id have to design things like a dropdown menu when hovering over the extension etc to choose between which player would be displayed on the top bar or something like that and whatever else pops up when working on it)

While its a good idea, im super short on time and i cant really work on something like that. Marking it as closed for now, maybe in the future! 

In the time being, there are other extensions like the [mpris-label](https://extensions.gnome.org/extension/4928/mpris-label/) extension, which may provide what you ask for (haven't really used it). Thanks for your suggestion!
