### ISSUE TITLE
Bug when load artist and song name

### ISSUE THREAD

**Issue by tokkenno** [Sonath21/spotify-controls#3]
When I open spotify the first time, the name of the artist and the song do not load correctly. It only happens to me sometimes. Other times it works perfectly. It is corrected as soon as I switch to another song, whether I do it from the app or from the extension, so I understand that it's probably just a synchronisation problem.

![Captura desde 2024-10-16 11-31-11](https://github.com/user-attachments/assets/2a4ae03e-05d0-4631-9937-359fb02947db)

**OS:** Fedora 40 (Gnome 46)
**Spotify:** 1.2.45.454.gc16ec9f6 (From [Flathub](https://flathub.org/apps/com.spotify.Client))
**Extension:** Version 5

**Comment by Sonath21** [comment]
Yeah, its a placeholder that shouldnt even be showing 99% of the time (and when it does show its for like 10 ms the first time you launch spotify ). I have the same spotify version and GNOME version and its working as intended for me (never happened), so it must be an OS thing (?), as im running Ubuntu 24.04.1. Will look into it and post again!

**Comment by Sonath21** [comment]
Ok i pushed a potential bug fix on the github page only (not on the official extensions.gnome.org page). Tell me if this new version works so i can push it to the extensions page aswell. Thanks

**Comment by tokkenno** [comment]
It's a sync bug, so it's hard to know if it's fixed by brute force... but I set the CPU to 100% to slow down the PC and made a quick script to open and close spotify 50 times... and it worked fine every time.

Seems to be fixed. Thank you very much!

**Comment by Sonath21** [comment]
Sounds good! Soon pushing a more refined fix to the extensions page as well. Thanks for pointing it out!
