### ISSUE TITLE
Icons at right of the GNOME top bar have a bigger gap between them with the extension enabled

### ISSUE THREAD

**Issue by AFCMS** [Sonath21/spotify-controls#4]
With the extension:

![image](https://github.com/user-attachments/assets/72aece18-77d3-412e-a344-f9d800801023)

Without:

![image](https://github.com/user-attachments/assets/aa100e76-fd50-4e21-9aad-a4e4d4840999)

It's only a slight difference but it triggers me.

**Comment by Sonath21** [comment]
Bug fixed on Version 8! Thanks for pointing it out!
