### ISSUE TITLE
Feature Request: Volume Control via Scroll Wheel

### ISSUE THREAD

**Issue by Her0-GitHub** [Sonath21/spotify-controls#6]
Hi there! First of all, thank you for this amazing extension! 🙌

## What I'd Like to See
I'd love the addition of a feature that allows users to adjust Spotify's volume using the scroll wheel. Specifically, it would be great if scrolling over the song title displayed in the top bar could **increase** or **decrease** the volume.

## Why This Would Be Awesome
This feature would provide a **quick and intuitive** way to control volume directly from the Gnome top bar, without needing to switch applications. Perfect for those moments when you want to make a quick adjustment while focusing on something else!

Thanks for considering this suggestion! 😊

**Comment by Sonath21** [comment]
hmm, while it's an interesting idea, you could just use the F keys (F5,F6 etc) to control the system volume no? Also, maybe it would be weird for users unaware of this feature, and when they accidentally do adjust the volume when hovering over the extension (by accidentally moving the scroll wheel) they think something else is wrong. 

All in all, while its possible to implement, it won't be easy to make it clear that it's a feature, and it could cause more confusion to some users than good. Thanks for your recommendation through!!
